### ISSUE TITLE
Changing breakpoints results in an error

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-ssg#12]
Changing the breakpoint values in the foundation-sites-6 codebase works fine, but changing them in this codebase results in the attached error. I believe I followed the documentation to a T (http://foundation.zurb.com/sites-6-docs/media-queries.html#default-media-queries).
![screen shot 2015-11-11 at 2 48 10 pm](https://cloud.githubusercontent.com/assets/729893/11103978/41fc4138-8883-11e5-8ed3-4cab9ab72500.png)

**Comment by gakimball** [comment]
Can you paste the code to show how you changed the defaults?

**Comment by designerdean** [comment]
You bet. Here it is. Lines 83-93 of _settings.scss. I just copied and pasted what's in the docs (http://foundation.zurb.com/sites-6-docs/media-queries.html#changing-the-breakpoints).

```
// Breakpoints
// -----------

$breakpoints: (
  small: rem-calc(0),
  medium: rem-calc(640),
  large: rem-calc(1024),
  xlarge: rem-calc(1200),
  xxlarge: rem-calc(1440),
);
$breakpoint-classes: (small medium large xlarge);
```

**Comment by gakimball** [comment]
Try making them pixel values for now—they get automatically converted to `em` values at the end. We can clarify this in the documentation, and also make sure the `em` converter doesn't choke on `rem` values.

**Comment by designerdean** [comment]
Oh wow...I feel silly. This appears to be the same as the other issue I submitted. You just have to put digit values in there and it will convert it to ems for you.

**Comment by gakimball** [comment]
Hah well it's all good, we don't explain it anywhere.

**Comment by gakimball** [comment]
Closing this, but I have an issue open to update `rem-calc()`: zurb/foundation-sites-6#277
